# fly.toml app configuration file generated for conferencevideo on 2023-07-04T19:35:19-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "conferencevideo"
primary_region = "mia"

[build]
  image = "flyio/hellofly:latest"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
